const ShopActionTypes = {
  UPDATE_COLLECTIONS_START: 'UPDATE_COLLECTIONS_START',
  UPDATE_COLLECTIONS_SUCCESS: 'UPDATE_COLLECTIONS_SUCCESS',
  UPDATE_COLLECTIONS_ERROR: 'UPDATE_COLLECTIONS_ERROR',
  
};

export default ShopActionTypes;